### ISSUE TITLE
`make debug-client` throws `Failed at the policyengine-client@1.32.4 start script`

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine#641]
```
Starting the development server...

events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)
Emitted 'error' event on ClientRequest instance at:
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:400:28)
    at TLSSocket.emit (domain.js:475:12)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -54,
  code: 'ECONNRESET',
  syscall: 'read'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! policyengine-client@1.32.4 start: `craco start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the policyengine-client@1.32.4 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/maxghenis/.npm/_logs/2022-04-08T15_50_44_282Z-debug.log
make: *** [debug-client] Error 1
```
[Full log](https://gist.github.com/MaxGhenis/0ccb2d54f16e0323a625ab4e2a65b103)

**Comment by MaxGhenis** [comment]
`nvm deactivate node; nvm uninstall node; nvm activate v14` fixed it

**Comment by MaxGhenis** [comment]
Actually this is now happening regularly. Reopening to identify a sticky solution.

**Comment by MaxGhenis** [comment]
Hasn't happened in a while
