### ISSUE TITLE
US `How earnings affect you` chart broken: `KeyError: 'household_benefits_baseline'`

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine#658]
Endless spinner, due to this error:
```
127.0.0.1 - - [16/Apr/2022 22:49:16] "GET /us/api/variables HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Apr/2022 22:49:16] "GET /us/api/variables HTTP/1.1" 200 -
INFO:PolicyEngine:entities completed in 0.0s.
127.0.0.1 - - [16/Apr/2022 22:49:16] "GET /us/api/entities HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Apr/2022 22:49:16] "GET /us/api/entities HTTP/1.1" 200 -
127.0.0.1 - - [16/Apr/2022 22:49:16] "GET /us/api/parameters HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Apr/2022 22:49:16] "GET /us/api/parameters HTTP/1.1" 200 -
127.0.0.1 - - [16/Apr/2022 22:49:27] "OPTIONS /us/api/household-variation?irs_income_bracket_rates_1=0.12 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Apr/2022 22:49:27] "OPTIONS /us/api/household-variation?irs_income_bracket_rates_1=0.12 HTTP/1.1" 200 -
127.0.0.1 - - [16/Apr/2022 22:49:28] "POST /us/api/household-variation?irs_income_bracket_rates_1=0.12 HTTP/1.1" 500 -
INFO:werkzeug:127.0.0.1 - - [16/Apr/2022 22:49:28] "POST /us/api/household-variation?irs_income_bracket_rates_1=0.12 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/maxghenis/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
    
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
    
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
    
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
    
KeyError: 'household_benefits_baseline'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/maxghenis/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/maxghenis/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/maxghenis/opt/anaconda3/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/maxghenis/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/maxghenis/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/maxghenis/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/maxghenis/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/maxghenis/opt/anaconda3/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/maxghenis/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/maxghenis/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/maxghenis/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/maxghenis/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/maxghenis/PolicyEngine/policyengine/policyengine/server.py", line 49, in new_fn
    result = fn(*args, **kwargs)
  File "/Users/maxghenis/PolicyEngine/policyengine/policyengine/server.py", line 75, in new_fn
    result = fn(*args, params=params, **kwargs)
  File "/Users/maxghenis/PolicyEngine/policyengine/policyengine/countries/country.py", line 424, in household_variation
    total_income,
  File "/Users/maxghenis/PolicyEngine/policyengine/policyengine/impact/household/charts.py", line 107, in budget_chart
    - df["household_tax_baseline"][i]
  File "/Users/maxghenis/opt/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 3458, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/Users/maxghenis/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'household_benefits_baseline'
```

**Comment by MaxGhenis** [comment]
I think https://github.com/PolicyEngine/policyengine/pull/607 is the culprit
